### ISSUE TITLE
Check clang-tidy build and functionality

### ISSUE THREAD

**Issue by gabrielefronze** [Open-ForBC/OpenForBC-Benchmark#155]

**Comment by iH8c0ff33** [comment]
It seems that the cpp-linter-action we're using is configured to build its image from the *Dockerfile* in the repo (see [action definition](https://github.com/shenxianpeng/cpp-linter-action/blob/3ad10e1add96e38e9bb25c6d713d37ddf0b90b9b/action.yml#L74)). The only way to stop building the image every time would be to fork the repo and create a new action which uses tagged images.
