### ISSUE TITLE
Real time benchmarks, get output fails with no match for stat "training_GPU_load"

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#192]
Error after running on GPU:

Epoch 50/50
469/469 [==============================] - 7s 15ms/step - loss: 0.0058 - sparse_categorical_accuracy: 0.9981
TRAINING COMPLETED!
  return dispatch_target(*args, **kwargs)
"MNIST_realtime_benchmark" preset "training" stats match failed: No match for stat "training_GPU_load" in benchmark output
ERROR: Benchmark "MNIST_realtime_benchmark" failed

**Comment by leggerf** [comment]
now only warning is issued #193

**Comment by leggerf** [comment]
similar for TeacherStudent

Iteration 9999
INFERENCE COMPLETED!
"TeacherStudent_realtime_benchmark" preset "inference" stats match failed: No match for stat "training_GPU_load" in benchmark output
WARNING: Stats decode for benchmark "TeacherStudent_realtime_benchmark" failed
Preset    Stat    Value
--------  ------  -------

**Comment by leggerf** [comment]
and CIFAR

50000/50000 [==============================] - 152s 3ms/step - loss: 1.3243 - accuracy: 0.5294
TRAINING COMPLETED!
"CIFAR_realtime_benchmark" preset "training" stats match failed: No match for stat "training_GPU_load" in benchmark output
WARNING: Stats decode for benchmark "CIFAR_realtime_benchmark" failed
Preset    Stat    Value
--------  ------  -------

**Comment by leggerf** [comment]
still to be done: 
- change the string: training_GPU_load -> load
- check and modify benchmark code accordingly

**Comment by leggerf** [comment]
sorry @iH8c0ff33, of course I found another one: [TCGA_topicmodeling](https://github.com/Open-ForBC/OpenForBC-Benchmark/tree/devel/benchmarks/TCGA_topicmodeling) .
Can you fix it as well pls?

**Comment by iH8c0ff33** [comment]
Ok, will do another PR.
