### ISSUE TITLE
Benchmarks' tests fail in CI because of bug

### ISSUE THREAD

**Issue by iH8c0ff33** [Open-ForBC/OpenForBC-Benchmark#207]
The CI workflow tries to run benchmark for all directories inside of
`benchmarks`, but some of them don't actually contain a benchmark.

**Comment by leggerf** [comment]
@iH8c0ff33 I think this can be closed, right?

**Comment by iH8c0ff33** [comment]
@leggerf Yes, tests for the blender PR passed after the fix was merged.
