### ISSUE TITLE
blender metal/gpu doesn't work

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#223]
I have this error:

./o4bc-bench benchmark run blender_benchmark  classroom_metal
Running "blender_benchmark" setup commands
$ python3 -m venv .venv
(venv) $ ./setup.sh
Requirement already satisfied: progressbar in ./.venv/lib/python3.9/site-packages (2.5)
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/home/legger/OpenForBC-Benchmark/benchmarks/blender_benchmark/.venv/bin/python3 -m pip install --upgrade pip' command.
(venv) $ ./setup.py
Initialising setup......
https://download.blender.org/release/BlenderBenchmark2.0/launcher/benchmark-launcher-cli-3.0.0-linux.tar.gz
Running "blender_benchmark" preset "classroom_metal"
(venv) $ bin/benchmark-launcher-cli blender download 3.1.0
Blender version already available locally: 3.1.0
(venv) $ bin/benchmark-launcher-cli scenes download -b 3.1.0 classroom
Scene already available locally: classroom
(venv) $ bin/benchmark-launcher-cli benchmark --json -b 3.1.0 --device-type METAL classroom
Warming up classroom
ERROR: An unexpected error occurred. Run with '--verbosity 3' for detailed logs.
ERROR: Did not receive Benchmark JSON Data.
Benchmark "blender_benchmark" preset "classroom_metal" command "bin/benchmark-launcher-cli benchmark --json -b 3.1.0 --device-type METAL classroom" failed
Task (venv) $ bin/benchmark-launcher-cli benchmark --json -b 3.1.0 --device-type METAL classroom failed with return code 1
ERROR: Benchmark "blender_benchmark" failed

Same if I run with GPU preset. The CPU preset works

**Comment by iH8c0ff33** [comment]
The metal preset is for macOS only (uses the Metal API)

**Comment by leggerf** [comment]
Also the gpu one?

Il giorno 28 Giu 2022, 20:08, alle ore 20:08, Daniele Monteleone ***@***.***> ha scritto:
>The metal preset is for macOS only (uses the Metal API)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Open-ForBC/OpenForBC-Benchmark/issues/223#issuecomment-1169057956
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by iH8c0ff33** [comment]
@leggerf I've now tested the `classroom_cuda` preset on linux and it works, can you try running the benchmark directly with the launcher (`bin/benchmark_launcher_cli` in the benchmark's folder) adding the `--verbosity 3` option?

**Comment by leggerf** [comment]
bin/benchmark-launcher-cli benchmark --json -b 3.1.0 --device-type CUDA classroom --verbosity 3
2022/06/30 14:57:52 metadata.go:14: Fetching Metadata: https://opendata.blender.org/benchmarks/metadata/
2022/06/30 14:57:52 metadata.go:49: Successfully fetched metadata
2022/06/30 14:57:52 metadata.go:71: Getting current launcher.
2022/06/30 14:57:52 checksum.go:16: Calculating checksum of current launcher.
2022/06/30 14:57:52 checksum.go:35: Launcher checksum: b4649a0deb95d1c611efa9c0b8b919c1554bf4220afcd8d754570533dd2b6672.
Warming up classroom
2022/06/30 14:57:52 benchmark.go:125: Starting benchmark.
2022/06/30 14:57:52 benchmark.go:126: blenderExecutable: "/home/jovyan/.cache/blender-benchmark-launcher/blender-versions/ced2aaabc75731c2ae0e29493d0d2db7803d2bbb70a11cd0e7f50546d465bd8c/blender-3.1.0-linux-x64/blender"
2022/06/30 14:57:52 benchmark.go:153: arguments: [--background --factory-startup -noaudio --debug-cycles --enable-autoexec --engine CYCLES /home/jovyan/.cache/blender-benchmark-launcher/scenes/936f0a528f03eba291c67ea87743a0ebde58938fb87471b262721b89b46b875d/classroom/main.blend --python /home/jovyan/.cache/blender-benchmark-launcher/benchmark-scripts/a21efa53425a47134b2a4af43302cdb5a6a5241a86f62b7c4efb7583eb170391/blender-benchmark-script-3.0.0/main.py -- --device-type CUDA --warm-up]
BLENDER: /home/jovyan/.cache/blender-benchmark-launcher/blender-versions/ced2aaabc75731c2ae0e29493d0d2db7803d2bbb70a11cd0e7f50546d465bd8c/blender-3.1.0-linux-x64/blender: error while loading shared libraries: libXi.so.6: cannot open shared object file: No such file or directory
ERROR: An unexpected error occurred. Run with '--verbosity 3' for detailed logs.

**Comment by leggerf** [comment]
do you know which package should install libXi.so.6? Possibly within pip or conda, since I do not have sudo rights on yoga
