### ISSUE TITLE
CLI: exit gracefully and navigation among varius options

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#37]
I did not find a way to exit gracefully from the CLI. If there is one, I missed it.
Also, I think it would be good to have a way to navigate through the various menus. For example, if I select a Benchmark suite, how do I go back to run a single benchmark?

**Comment by aneesh404** [comment]
I see the problem here. I'm on it.

**Comment by leggerf** [comment]
navigation still not possible, but possibility to quit certainly makes it way better
