### ISSUE TITLE
Add documentation to Blender benchmark

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#45]
Add at least a README file to document the Blender benchmark (can of couse also link to original documentation), what the various settings do, and what the setup file does.
For example, it is not clear when it asks if you want to execute the setup file, what this is supposed to do.

**Comment by aneesh404** [comment]
The setup file is a modification we added while solving #19 . I can put print statements to list out what's happening in the background + add to developer docs why setup is there. Is that fine?

**Comment by leggerf** [comment]
I still don't understand:
what is the difference of using the setup file or not? In other words, what happens if I answer yes, and what happens if I answer no?

And yes, adding explanations to the printout and to the doc is necessary, otherwise how is a user supposed to make the choice?

**Comment by aneesh404** [comment]
So if you agree to running setup file, it initializes/downloads the executables and other contents. It was just to de clutter the main implementation and make it an option given to the user.
Yes, I totally agree, will make the needful changes.

**Comment by leggerf** [comment]
Setup file issue solved in PR 57

**Comment by leggerf** [comment]
README added in #55
