### ISSUE TITLE
shell completion?

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#74]
I see that there are this commands available in CLI:

python3 user_interfaces/cli.py --install-completion bash
python3 user_interfaces/cli.py  --show-completion bash

but I wasn't able to use them, or at least shell completion didn't work. Can you pls add to the user documentation how this options should be used?

**Comment by aneesh404** [comment]
The completion works on linux for me, but I can't get it to work on powershell. The commands followed were
1. python -m pip install typer-cli
2. typer --install-completion
