### ISSUE TITLE
broken link in blender doc

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#75]
link to https://github.com/Open-ForBC/OpenForBC-Benchmark/blob/devel/benchmarks/blender_benchmark/bin/README.txt
is broken (in blender_benchmark/README.md)

**Comment by aneesh404** [comment]
The readme is downloaded with the executables hence would link to nothing until blender is run atleast once.
Would you like me to remove it? It's anyway just for reference.

**Comment by leggerf** [comment]
Then just commit it to git (maybe in another location to avoid conflicts) and point to that. People are going to use the readme from the github website, therefore that link is not useful as it is
