### ISSUE TITLE
CLI command list-logs not working and not documented

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#79]
python3 user_interfaces/cli.py list-logs
+-------+------+-----------+
| Index | Date | Benchmark |
+-------+------+-----------+
+-------+------+-----------+

shows empty logs, whereas my logs/ folder is not empty.
This command is also not documented in the user guide

**Comment by aneesh404** [comment]
The listing function for logger got broken since we changed the date format, I'll fix it right away.

**Comment by leggerf** [comment]
so, this stresses even more the importance of automatically testing features when making changes. To avoid break working parts.
In any case, have a look at the doc, and if you give green light on that, I'll close this issue
