### ISSUE TITLE
Logs for suites or suites not running all benchmarks?

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#84]
I created a suite that runs blender twice:

{
    "name": "Blender benchmark suite",
    "description": "A preconfigured suite running the same benchmark with two settings",
    "benchmarks": [
        {
            "name": "blender_benchmark",
            "settings": "settings1.json"
        },
        {
            "name": "blender_benchmark",
            "settings": "settings2.json"
        }
    ]
}

but it seems to me it logs only one run:

{
    "output": [
        {
            "timestamp": "2021-08-18T09:44:45.330873+00:00",
            "stats": {
                "device_peak_memory": 146,
                "total_render_time": 689.48,
                "render_time_no_sync": 685.452
            },
            "blender_version": {
                "version": "2.92.0",
                "build_date": "2021-02-25",
                "build_time": "09:31:37",
                "build_commit_date": "2021-02-24",
                "build_commit_time": "16:25",
                "build_hash": "02948a2cab44",
                "label": "2.92",
                "checksum": "2cd17ad6e9d6c241ac14b84ad6e72b507aeec979da3d926b1a146e88e0eb3eb4"
            },
            "benchmark_launcher": {
                "label": "2.0.5",
                "checksum": "0513a4a626bb0ee387366f67a632ea0f886ee5906aaafe148d473842059fb2ec"
            },
            "benchmark_script": {
                "label": "2.0.1",
                "checksum": "dee17c82d883838f6da21e7c86f368cda2ab8399eac10b660e199628aca09ec0"
            },
            "scene": {
                "label": "bmw27",
                "checksum": "bc4fd79cbd85a1cc47926e848ec8f322872f5c170ef33c21e0d0ce303c0ec9ea"
            }
        }
    ]
}

can you pls check?

**Comment by leggerf** [comment]
Actually, maybe the problem is that the suite is not running all benchmarks?

For example suite_2 should run 4 times dummy_benchmark and it outputs only once:

python3 user_interfaces/cli.py run-suite example_suite_2.json
Hello world!!!

**Comment by aneesh404** [comment]
Yes that was the case (It was forced to use default settings given in benchmark_info), it supports your point about urgency of tests. Now that it's fixed and I'm halfway done with #68 I guess I can take up #78 to make sure this doesn't happen any more.

**Comment by leggerf** [comment]
yes, I think this is really important now, since as soon as the code makes more things, it gets easier to break it when fixing something else or implementing new features.
Let me know when #85 is ready

**Comment by aneesh404** [comment]
Yes, I'm trying to thoroughly test it with combination of benchmarks and all the scenes in blender, I'll remove the draft option once the execution end
