### ISSUE TITLE
blender victor scene doesn't work

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC-Benchmark#97]
@aneesh404 do you know what is happening?

BLENDER: Fra:2472 Mem:5437.86M (Peak 5596.74M) | Time:00:37.23 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | GEO-franck_sheep_furcoat
BLENDER: Fra:2472 Mem:5623.98M (Peak 5623.98M) | Time:00:37.24 | Mem:0.00M, Peak:0.00M | Scene, RenderLayer | Synchronizing object | GEO-rope_mesh
ERROR: An unexpected error occurred. Run with '--verbosity 3' for detailed logs.
ERROR: Did not receive Benchmark JSON Data.
Traceback (most recent call last):
  File "user_interfaces/cli.py", line 348, in <module>
    app()
  File "/home/legger/.local/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/legger/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/legger/.local/lib/python3.6/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "user_interfaces/cli.py", line 202, in run_benchmark
    bmark=benchmark, settings=settings, verbosity=verbose
  File "/home/legger/OpenForBC-Benchmark/user_interfaces/interface_skeleton.py", line 21, in startBenchmark
    return benchmarkObject.startBenchmark(verbosity)
  File "/home/legger/OpenForBC-Benchmark/benchmarks/blender_benchmark/implementation.py", line 83, in startBenchmark
    s = eval(s)
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

**Comment by aneesh404** [comment]
Hi, as previously discussed on text, the benchmark crashes my laptop each time I run, which I think is due to the memory utilization by the scene. 
How much VRAM does your gpu have?

**Comment by leggerf** [comment]
2GB. It doesn't crash for me, it just exits with the error posted above (quite at the beginning if you look at the time stamp). I'm wondering if you have suggestions how to debug it, because it isn't clear if it is a problem of blender, or our benchmark code.
In the sense, it should be clear from the error message that it was blender that crashed.

**Comment by leggerf** [comment]
what is printing this line:
ERROR: An unexpected error occurred. Run with '--verbosity 3' for detailed logs.
ERROR: Did not receive Benchmark JSON Data.
?

**Comment by aneesh404** [comment]
Yes, I tried to look up for any known errors for victor but I couldn't find any. The error logs suggest that it's a problem from blenders end. I tried debugging but my system bricks even before the scene starts benchmark execution.

**Comment by leggerf** [comment]
Can you try to catch the error and throw a more meaningful error? Can you reproduce the error by running blender outside of the benchmark code? I guess you're building a command line? Can you share it? I would like to try to run blender standalone

**Comment by aneesh404** [comment]
I tried runnning blender using it's cli, outside out tool. It's returning the same error as above, ie 
```ERROR: An unexpected error occurred. Run with '--verbosity 3' for detailed logs.
ERROR: Did not receive Benchmark JSON Data.```

**Comment by aneesh404** [comment]
Let me try running it for all blender versions, if it doesn't work for all can we get rid of the scene in blender readme?

**Comment by aneesh404** [comment]
I tried running blender versions - [2.93,2.92,2.91.2,2.90.1,2.81,2.83] and all of them show this error.

**Comment by leggerf** [comment]
@aneesh404 I think this is ok, but we should also solve the issue in a general way, i.e. if any benchmark (not only blender) exits with an error, our software should be able to catch the error and exit with an error message. For example in this case:
"The benchmark exited with exit code XX and error message YYY". I will open a new issue for that
